services:
  nats:
    image: docker.io/nats:${NATS_VERSION:-2.11-alpine}
    restart: always
    expose:
      - 4222
      - 8222
      - 6222
    # healthcheck:
    #   test: ["CMD", "nc", "-zv", "-w", "10", "nats", "4222"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 10
    #   start_period: 30s
    command: --http_port 8222
    ports:
      - "${NATS_BIND_IP:-127.0.0.1}:${NATS_PORT_NUMBER:-4222}:4222"
  nats-exporter:
    image: docker.io/natsio/prometheus-nats-exporter:${NATS_EXPORTER_VERSION:-0.17.3}
    depends_on:
      - nats
    expose:
      - 7777
    command:
      - -healthz
      - -varz
      - "http://nats:8222"
  mongodb-fix-permission-container:
    image: docker.io/mongodb/mongodb-community-server:${MONGODB_VERSION:-8.2}-ubi8
    restart: on-failure
    user: "0"
    volumes:
      - ${MONGODB_HOST_PATH:-mongodb_data}:/data/db:rw
    entrypoint: |
      sh -xc '
        owner="$(stat -c %u /data/db)";
        # for fresh installs
        if [ "$$owner" != "1001" ]; then
          echo "=====> Fixing directory ownership"
          chown -R 1001 /data/db;
        else echo "=====> Nothing to do"; fi;
      '
  mongodb-replicaset-init-container:
    image: docker.io/mongodb/mongodb-community-server:${MONGODB_VERSION:-8.2}-ubi8
    restart: on-failure
    depends_on:
      mongodb:
        condition: service_healthy
    user: "0"
    environment:
      MONGODB_REPLICA_SET_NAME: ${MONGODB_REPLICA_SET_NAME:-rs0}
      MONGODB_PORT_NUMBER: ${MONGODB_PORT_NUMBER:-27017}
      MONGODB_INITIAL_PRIMARY_HOST: ${MONGODB_INITIAL_PRIMARY_HOST:-mongodb}
    volumes:
      - ${MONGODB_HOST_PATH:-mongodb_data}:/data/db:rw
    entrypoint: |
      sh -xc '
        echo "=====> Initiating ReplSet $$MONGODB_REPLICA_SET_NAME at $$MONGODB_INITIAL_PRIMARY_HOST:$$MONGODB_PORT_NUMBER...";
        mongosh --eval "rs.initiate({_id: \"$$MONGODB_REPLICA_SET_NAME\", members: [{ _id: 0, host: \"$$MONGODB_INITIAL_PRIMARY_HOST:$$MONGODB_PORT_NUMBER\" }]})" --host mongodb --port $$MONGODB_PORT_NUMBER;
        echo "=====> Initiating ReplSet done...";
      '
        
  mongodb:
    image: docker.io/mongodb/mongodb-community-server:${MONGODB_VERSION:-8.2}-ubi8
    restart: always
    depends_on:
      mongodb-fix-permission-container:
        condition: service_completed_successfully
    volumes:
      - ${MONGODB_HOST_PATH:-mongodb_data}:/data/db:rw
    user: "1001"
    environment:
      MONGODB_REPLICA_SET_NAME: ${MONGODB_REPLICA_SET_NAME:-rs0}
      MONGODB_PORT_NUMBER: ${MONGODB_PORT_NUMBER:-27017}
      MONGODB_INITIAL_PRIMARY_HOST: ${MONGODB_INITIAL_PRIMARY_HOST:-mongodb}
    command:
    - --replSet
    - ${MONGODB_REPLICA_SET_NAME:-rs0}
    - --bind_ip_all
    healthcheck:
      test: ["CMD", "mongosh", "--host", "mongodb", "--port", "${MONGODB_PORT_NUMBER:-27017}", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s
    ports:
      - "${MONGODB_BIND_IP:-127.0.0.1}:${MONGODB_PORT_NUMBER:-27017}:${MONGODB_PORT_NUMBER:-27017}"

  mongodb-exporter:
    image: docker.io/percona/mongodb_exporter:${MONGODB_EXPORTER_VERSION:-0.44.0}
    depends_on:
      - mongodb
    expose:
      - 9216
    command:
      - --mongodb.uri=${MONGODB_URI:-mongodb://mongodb:27017}
      - --collect-all
      - --compatible-mode
volumes:
  mongodb_data: {driver: local}
