http:
  routers:
    rocketchat:
      entryPoints:
        - http
      service: rocketchat
      rule: Host(`{{ env "DOMAIN" }}`)
    grafana:
      entryPoints:
        - http
      rule: Host(`{{env "GRAFANA_DOMAIN"}}`)
      service: grafana
  services:
    rocketchat:
      loadBalancer:
        servers:
          - url: "http://rocketchat:3000"
    grafana:
      loadBalancer:
        servers:
          - url: "http://grafana:3000"
